spring.application.name=veriflow
# PostgreSQL
spring.datasource.url=jdbc:postgresql://localhost:5432/veriflow
spring.datasource.username=postgres
spring.datasource.password=postgres
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA / Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

# Logging (da lepo vidi? SQL i evente)
logging.level.org.hibernate.SQL=DEBUG
logging.level.org.hibernate.type.descriptor.sql=TRACE

# (Ako imate Spring Security i ?elite da bude otvoreno za hackaton demo, kasnije doda? properti/profil za "permitAll")

